### ISSUE TITLE
Debemos entrar a recopilar data de Ivu?

### ISSUE THREAD

**Issue by aallfredo** [aallfredo/DebesAlgo#12]
¿La gente le tire foto a su recibo para pasarle a hacienda luego los ivus de los sitios?

¿Valdra la pena hacerlo?

¿Podemos darle un sistema de rewards?

**Comment by edwardbetan** [comment]
This guy has some pretty good tutorials on how to OCR an image: http://www.pyimagesearch.com/  I've used tesseract previously: https://github.com/tesseract-ocr/tesseract .  Key here is finding an incentive method. I have a codebase that does some of this. Let me dig it up and put it in a branch.

Here's the tutorial: http://www.pyimagesearch.com/2014/09/01/build-kick-ass-mobile-document-scanner-just-5-minutes/

**Comment by aallfredo** [comment]
Nice!!

**Comment by aallfredo** [comment]
Creo que esto no lo vamos a acabar haciendo. Cerrandolo por ahora
