### ISSUE TITLE
Crear un Slack chat o Gitter chat para este repositorio

### ISSUE THREAD

**Issue by jorluiseptor** [aallfredo/DebesAlgo#18]
Sugerencia, podemos crear un chat en Slack o Gitter asociada a este repositorio para chatear/discutir alla. Saludos. https://slack.com/ o https://gitter.im/

**Comment by aallfredo** [comment]
@jorluiseptor no se si hay uno de programadores de puerto rico en general porque podriamos simplemente usar ese.

**Comment by aallfredo** [comment]
@jorluiseptor decidiste lo que querias hacer con esto ?

**Comment by jorluiseptor** [comment]
Suena bien tu idea. A mí me da igual crear un chat general en Slack para programadores de PR. Lo que no sé si habra uno ya y lo otro es que si "canibalizaremos" el grupo de facebook pq se moverian al Slack.  Qué tu crees?

**Comment by jorluiseptor** [comment]
Bueno, que se chave, lo hice: http://prdevelopers.slack.com. Dame tu email.

**Comment by jorluiseptor** [comment]
aqui un demo de lo que es slack https://slack.com/is

**Comment by aallfredo** [comment]
Creo que esta bien. Lo que propusiste en FB.

**Comment by aallfredo** [comment]
Cerrandolo porque @jorluiseptor ya lo seteo.
