### ISSUE TITLE
Hacer paginas de admin y de manejar articulos funcionar en mobil.

### ISSUE THREAD

**Issue by aallfredo** [aallfredo/DebesAlgo#19]
Ahora mismo de la forma que estan estan super dificil de usar desde el celular.

**Comment by aallfredo** [comment]
@jorluiseptor esta es la que estas bregando.

**Comment by jorluiseptor** [comment]
Cómo marco esto como indevelopment?

**Comment by aallfredo** [comment]
@jorluiseptor solo te lo asignas y ya. Si tiene asignee ya alguien lo esta haciendo. Crees que esto cae para el 17?
