### ISSUE TITLE
Modificar el README.md para invitar a colaboradores al DebesAlgo room de Slack

### ISSUE THREAD

**Issue by jorluiseptor** [aallfredo/DebesAlgo#21]
Sugiero que añadan una invitación a colaboradores en el README.md. Algo como: 

_Si deseas unirte a la discusión de este proyecto y otros, únete a nuestro Slack chat: https://prdevelopers.slack.com/. Para registarse, visite https://prdevelopers.herokuapp.com/._

**Comment by aallfredo** [comment]
Haz un pull puedes editar el file directo desde github.

**Comment by jorluiseptor** [comment]
Dale

**Comment by jorluiseptor** [comment]
Ahi lo hize. Checkitout.

**Comment by aallfredo** [comment]
Lo acepte cerrando esto. :)
