### ISSUE TITLE
Error cuando me registro

### ISSUE THREAD

**Issue by jorluiseptor** [aallfredo/DebesAlgo#22]
Me sale este error cuando corro la solucion localmente y trato de registarme: 

![image](https://cloud.githubusercontent.com/assets/4360992/12061593/6753a362-af58-11e5-9845-de28c50fee1e.png)

**Comment by aallfredo** [comment]
Estoy investigando esto pero lamentablemente la laptop que tengo es una tortuga y lleva como 4 horas instalando VS community.

**Comment by aallfredo** [comment]
Asegurate que tienes esto instalado porque es lo que emula azure en tu maquina. Microsoft Azure SDK for .NET

https://azure.microsoft.com/en-us/downloads/

**Comment by jamesxv7** [comment]
@jorluiseptor Puedes confirmar si se ha creado el database? 

![debesalgo](https://cloud.githubusercontent.com/assets/121668/12069037/effdba1e-aff2-11e5-9237-0190c6010f42.PNG)

**Comment by aallfredo** [comment]
@jamesxv7 ese es el archivo donde esta crea la base de datos.

**Comment by jorluiseptor** [comment]
no. no aparece na' ahí

![image](https://cloud.githubusercontent.com/assets/4360992/12069110/5d62d0d6-afed-11e5-9586-080319675154.png)

**Comment by aallfredo** [comment]
@jorluiseptor mira mi comentario encima del de james. Instale eso en la maquina que acabo de setear con community y despues ya corrio.

**Comment by aallfredo** [comment]
link directo sdk http://go.microsoft.com/fwlink/?linkid=518003&clcid=0x409

**Comment by aallfredo** [comment]
@jorluiseptor vamos a poner el link del sdk en las instrucciones y con eso creo que estamos.

**Comment by jamesxv7** [comment]
Corrigeme si me equivoco pero para poder correr el proyecto de manera local se debe tener Sql Express instalado para que el Entity Framework pueda crear el database. El error indica que no encuentra un archivo. Me sospecho que es el .mdf.

**Comment by aallfredo** [comment]
Le di update al readme voy a cerrar esto.
