### ISSUE TITLE
Añadir total adeudado

### ISSUE THREAD

**Issue by jorluiseptor** [aallfredo/DebesAlgo#29]
Podemos añadir un total de lo que todos los negocios deben como un detalle adicional. Para esto necesitaríamos un campo especial para cantidad adeudada.

**Comment by aallfredo** [comment]
Tasks:
1. Hay que crear un campo en la base de dato y modificar las paginas que lo ensenan
2. tambien hay que por cada establecimiento y añadir la cantidad adeudada que se reporto

**Comment by aallfredo** [comment]
@jorluiseptor el servicios es /ClosedBusiness

E.g de outpout abajo el campo que te importa es el que dice summary para el google graph SummaryOfDebtPerTowns

{"Businesses":[{"Id":1,"Name":"Dominos Pizza","Address":"San Juan","DateClosed":"2015/12/1985","CurrentStatus":0,"CurrentStatusText":"Open","ArticleLink":"http://www.primerahora.com/noticias/gobierno-politica/nota/haciendaembargatresdominospizzayalarecibolighthouse-1127206/","Img":"http://rec-eph.gfrcdn.net/images/tnph3/615/304/1/1/615/304/2015/12/18/dominos-embargado-2.png","Details":"test","Owner":null,"TotalMoneyOwed":12.00},{"Id":3,"Name":"tatattat","Address":"Isabela San Juan","DateClosed":null,"CurrentStatus":0,"CurrentStatusText":"Open","ArticleLink":null,"Img":null,"Details":null,"Owner":null,"TotalMoneyOwed":0.00}],"SummaryOfDebtPerTowns":{"San Juan":12.00,"Isabela":0.00},"TownTags":["Isabela","San Juan"]}

**Comment by aallfredo** [comment]
Done!
