### ISSUE TITLE
Add login link

### ISSUE THREAD

**Issue by jorluiseptor** [aallfredo/DebesAlgo#34]
As a registered user, I need to see a link to the login screen so that I can sign in. Right now, I don't know the exact URL and can't log in.

**Comment by aallfredo** [comment]
Esto es intencional ahora mismo. Porque no hay nada para usuarios logged in. Solamente si eres admin en el sistema tienes alguna opcion.

**Comment by aallfredo** [comment]
Done on Jan31 release
