### ISSUE TITLE
Create an account on Google Webmaster Tools and Google Analytics for this site

### ISSUE THREAD

**Issue by jorluiseptor** [aallfredo/DebesAlgo#36]
Create an account on Google Webmaster Tools and Google Analytics websites for this website and add metatags to this site to start tracking site usage.

**Comment by jorluiseptor** [comment]
Si creas las cuentas y me das la info, yo la añado. O si creas las cuentas y me añades a mí, jorluiseptor@gmail.com como admin yo me encargo del resto.

**Comment by aallfredo** [comment]
ya hay una entrada de analytics.

**Comment by jorluiseptor** [comment]
Perfect. Cuando puedas me das el ID. Tienes una en Google Webmaster Tools?

**Comment by aallfredo** [comment]
Esta puesto en la pagina en el template file.

**Comment by aallfredo** [comment]
te a~nadi.

**Comment by aallfredo** [comment]
@jorluiseptor en google webmaster tools nope.

**Comment by jorluiseptor** [comment]
ah, sí, ya veo que esta en la página. No sé si entonces quieras anadir WebMasterTools.

**Comment by aallfredo** [comment]
Como quieras nunca las he usado.

**Comment by jorluiseptor** [comment]
The verification code is added to origin/develop. When the site is published I will finish the verification, add you to the admins in WebMaster tools site. Will leave this open until that happens, but code is finished.

**Comment by aallfredo** [comment]
Awesome! Puede ser que haga deploy un poco tarde manana.

**Comment by aallfredo** [comment]
@jorluiseptor esto esta en prod.

**Comment by jorluiseptor** [comment]
Confirmed that works and added @aallfredo as admin.
