### ISSUE TITLE
Marcar si el establecimiento está cerrado o abierto

### ISSUE THREAD

**Issue by jamesxv7** [aallfredo/DebesAlgo#8]
Se de varios establecimientos que a pesar del embargo están operando. Otros no han pasado por la misma suerte. Sería bueno poder tener la opción de marcar o mostrar (ya se que el team de Debes Algo confirme) si el establecimiento está operando o permanece cerrado.

**Comment by aallfredo** [comment]
Creo que esto es un duplicado de https://github.com/aallfredo/DebesAlgo/issues/5

El campo esta en debesalgo.Models.ClosedBusiness 

Es un enum que se llama Status estaba pensando que esto lo ponemos luego de permitir a los usuarios registrar cambios debido ahora mismo con la data que he sacado del periodico ahora mismo no tengo suficiente info.

**Comment by aallfredo** [comment]
En develop

**Comment by aallfredo** [comment]
done jan 31
